### PR TITLE
move default value of data_key fetch to block

### PR DESCRIPTION
**Pull request by StoneFrog**

### CODE REVIEW

**Comment by Azdaroth** [comment]
@StoneFrog What's the need?

**Comment by StoneFrog** [comment]
@Azdaroth 
crashes specs on one of the apps since loads model before loading schema. As a result it tries to access column_names but there is no such table in db at that point which causes all operation to fail

**Comment by Azdaroth** [comment]
@StoneFrog Does this thing looks familiar? https://github.com/BookingSync/bsa-invoices/blob/b7441535221102a7778281376b4d0fad8750227f/app/models/concerns/rescueable_from_undefined_table_error.rb  The exception was `ActiveRecord::StatementInvalid` ?

**Comment by Azdaroth** [comment]
`@StoneFrog StoneFrog deleted a comment from Azdaroth 17 seconds ago` :doge:

**Comment by thilonel** [comment]
@StoneFrog what's the error that got raised?

**Comment by StoneFrog** [comment]
@thilonel 
`ActiveRecord::StatementInvalid: PG::UndefinedTable` Why do you ask?

**Comment by thilonel** [comment]
@StoneFrog just to know, in case.

**Comment by StoneFrog** [comment]
@thilonel Will be helpful if you use jsonapi resources.

**Pull request merged**
