### PR TITLE
transaction_per_page returns all processed objects

### PR DESCRIPTION
**Pull request by thilonel**

### CODE REVIEW

**Comment by StoneFrog** [comment]
@thilonel Why do we need this change? If I remember correctly, this was the main problem with auto_paginate - storing all records was eating too much memory in case of huge collections

**Comment by thilonel** [comment]
@StoneFrog ah that is also true... why I personally need this, is because my app does:
```ruby
  def self.synchronize(*)
    super.tap do |collection|
      collection.each do |rates_rule|
```

**Comment by StoneFrog** [comment]
@thilonel Take a look at the hook `handle_processed_objects_proc`. You can pass proc and it'll execute operation on each batch

**Comment by thilonel** [comment]
Nice! I was too much in a rush, should've stopped to think first. Thank you!

**Pull request closed without merging**
